name = "DETH Additions"
author = "Chronophylos"
prefix = "dta"
mainprefix = "z"

[files]
include = ["LICENSE", "meta.cpp", "mod.cpp", "README.md", "CHANGELOG.md"]

[version]
git_hash = 0

[lints.sqf.var_all_caps]
options.ignore = ["PREP_RECOMPILE_*"]
