name: Build

on:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT build
        run: hemtt release
      - name: Remove 'latest'
        run: rm release/dta-latest.zip
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: dta-latest
          path: release/dta-*.zip

  release-github:
    name: Release on GitHub
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
      - name: Create Release Version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-workshop:
    name: Release on Steam Workshop
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dta-latest
          path: release.zip
      - name: Unzip Artifact
        run: unzip release.zip
      - name: Release
        uses: arma-actions/workshop-upload@v1
        with:
          appId: "107410"
          itemId: "3332303157"
          contentPath: "release"
          changelog: "tba"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
